### PR TITLE
added blank readme and csv of fairness measures to make gist table for medium

### PR DESCRIPTION
**Pull request by jhenderson-cs**

### CODE REVIEW

**Comment by cdraper-CS** [comment]
Why not use Certifai to calculate disparate impact and equal opportunity fairness?

**Comment by jhenderson-cs** [comment]
My thought is that since Certifai is a diagnostic tool and AIF 360 is both
a diagnosis and mitigation tool, it’d be nice for users to have a thing to
use once they’ve identified unfairness. I can be more explicit about that
though. Would it be better if I say Certifai also has these measures, but
we want the user to have mitigation tools at the end of the process too?

**Comment by cdraper-CS** [comment]
The impression it gives now is that Certifai only deals with a small part of what people need for fairness and that they will need AIF360 to do what we recommend. It would be preferable to actually use Certifai for all three measures.  The blog doesnt talk about mitigating at all - that could potentially be a part 2.

**Comment by jhenderson-cs** [comment]
That makes sense--I've switched the calculations to all use Certifai and updated the tables, notebook, and readme accordingly.

**Review by cdraper-CS — APPROVED** [review]

**Review by valexiev-cs — COMMENTED** [review]
For the notebook:
- "to install visit" feels like should have a comma between "install" and "visit"
- The title and link are not updated yet (I assume that's on purpose, but pointing it out just in case)
- "tDisparate" -> "Disparate"

Also, that `__pycache__` folder should be added to the `.gitignore`

Looks good otherwise!

**Comment by jhenderson-cs** [comment]
Fixed the typos and added a `.gitignore`--thanks! I'll add the link and title once it's finalized.

**Review by valexiev-cs — APPROVED** [review]
LGTM

**Review by sdraper-CS — APPROVED** [review]
Looks good apart from a few minor comments below, but I don't think we should merge to master until you have the blog URLs to fill in the links.

1. I think in the scan creation the name 'test_user_case' is a typo (possibly cut & paste from elsewhere) and should be 'test_use_case' (or could choose a more appropriate name)
2. When running the scan I'd drop the comments after `# Run the scan` as they are cut&paste from a teaching example about the API but not really relevant here

**Review by skottaram-cs — APPROVED** [review]

**Pull request merged**
